# Generated by Django 4.2.1 on 2023-05-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=40)),
                ("description", models.TextField()),
                ("age", models.IntegerField()),
                ("experience", models.PositiveIntegerField()),
                ("birth_date", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_manager", models.BooleanField(null=True)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
