# Generated by Django 4.2.1 on 2023-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_employee_is_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
