# Generated by Django 4.2.1 on 2023-05-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_nullblankdemo_alter_employee_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
