# Generated by Django 4.2.1 on 2023-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_employee_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="level",
            field=models.CharField(
                choices=[("jur", "Junior"), ("mid", "Middle"), ("sen", "Senior")],
                default="jur",
                max_length=3,
            ),
        ),
    ]
