# Generated by Django 4.2.1 on 2023-05-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_department_alter_employee_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="project",
            field=models.ManyToManyField(to="web.project"),
        ),
    ]
