# Generated by Django 4.2.1 on 2023-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_custom_add_data_slug_20230601_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
