# Generated by Django 4.2.2 on 2023-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="password",
            field=models.CharField(default="def_pass", max_length=50),
            preserve_default=False,
        ),
    ]
