# Generated by Django 4.2.2 on 2023-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_person_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(default=12),
        ),
    ]
