version: '3.4'

# NOTE: When connecting to the postgres docker container in the web interface,
# try using 'postgres' as the host name instead of 'localhost' or 'host.docker.internal'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Taralej1
      POSTGRES_USER: postgres-user
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    user: "${UID}:${GID}"  # to avoid permission issues
    environment:
      PGADMIN_DEFAULT_EMAIL: ivan.ivanov@softuni.bg
      PGADMIN_DEFAULT_PASSWORD: Taralej1
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - "5433:80"
    depends_on:
      - postgres