# Generated by Django 4.2.2 on 2023-06-20 16:38

import django.core.validators
from django.db import migrations, models
import preparation_project.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_name", models.CharField(max_length=30, unique=True)),
                ("artist", models.CharField(max_length=30)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("pop", "Pop Music"),
                            ("jazz", "Jazz Music"),
                            ("rnb", "R&B Music"),
                            ("rock", "Rock Music"),
                            ("country", "Country Music"),
                            ("dance", "Dance Music"),
                            ("hiphop", "Hip Hop Music"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField()),
                (
                    "price",
                    models.FloatField(
                        validators=[
                            preparation_project.web.validators.CustomFloatPositiveValidator
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(15),
                            preparation_project.web.validators.TextContainsOnlyAlphaNumericAndUnderscoreValidator(),
                        ]
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
