# Generated by Django 4.2.2 on 2023-06-20 18:33

from django.db import migrations, models
import django.db.models.deletion
import preparation_project.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="profile",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="web.profile"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="album",
            name="price",
            field=models.FloatField(
                validators=[
                    preparation_project.web.validators.CustomFloatPositiveValidator()
                ]
            ),
        ),
    ]
