# Generated by Django 4.2.2 on 2023-06-13 17:39

from django.db import migrations, models
import forms_demos_second.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="todomodel",
            name="priority",
            field=models.IntegerField(
                validators=[
                    forms_demos_second.web.validators.ValueInRangeValidator(2, 100)
                ]
            ),
        ),
    ]
