# Generated by Django 4.2.2 on 2023-06-13 18:01

from django.db import migrations, models
import forms_demos_second.web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_imagemodel_alter_todomodel_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=forms_demos_second.web.models.dynamic_upload_to_user_folder,
            ),
        ),
    ]
