# Generated by Django 4.2.2 on 2023-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_documentmodel_alter_imagemodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="todomodel",
            name="url_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
