# Generated by Django 4.2.2 on 2023-06-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_todomodel_url_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PhotoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pets_photos/"),
                ),
                ("alt_text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="photos",
                        to="web.petmodel",
                    ),
                ),
            ],
        ),
    ]
