# Generated by Django 4.2.2 on 2023-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_petmodel_photomodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="petmodel",
            name="linked_photos",
            field=models.ManyToManyField(
                blank=True, related_name="pets", to="web.photomodel"
            ),
        ),
    ]
