# Generated by Django 4.2.2 on 2023-06-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_petmodel_linked_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photomodel",
            name="pet",
        ),
        migrations.AddField(
            model_name="photomodel",
            name="pet",
            field=models.ManyToManyField(related_name="photos", to="web.petmodel"),
        ),
    ]
